name: zed-wg # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: "0.141.3" # just for humans, typically '1.2+git' or '1.3.2'
summary: Zed is a high-performance, multiplayer code editor.
description: |
  Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter. It's also open source.

grade: stable # must be 'stable' to release into candidate/stable channels
# confinement: devmode # use 'strict' once you have the right plugs and slots
confinement: classic

parts:
  zed:
    plugin: rust
    source-type: git
    source: https://github.com/zed-industries/zed.git
    source-tag: v0.141.3
    override-build: |
      rustup target add wasm32-wasi
      snapcraftctl build
    build-packages:
      - gcc
      - g++
      - libasound2-dev
      - libfontconfig-dev
      - libwayland-dev
      - libxkbcommon-x11-dev
      - libssl-dev
      - libzstd-dev
      - libvulkan1
      - libgit2-dev
      - clang
      - mold
    stage-packages:
      - libasound2
      - libxkbcommon-x11-0
    build-attributes:
      - enable-patchelf

apps:
  zed-wg:
    command: zed
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
